name: Continuous Integration

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # # First you need to install a chromium browser in your runner
      # - name: Install Chromium
      #   run: sudo apt-get install chromium-browser firefox openjdk-8-jdk

      # You fetch the current ref
      - name: Checkout
      - uses: actions/checkout@v2

      # Use Node version above 14.x you want to use
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Install your dependencies (with yarn, npm no matter)
      - run: npm install
        name: Install dependencies

      # Run your test with the same command you uses locally
      - run: npm run test:ci
        name: Running E2E tests
