name: Continuous Integration

on:
  push:
    branches:
      - "**"

env:
  # Temporarily add poc pipeline url Todo: update when actual environment is ready
  process.env.SERVICE_URL: https://registerwebapp.agreeableflower-aab4eacd.uksouth.azurecontainerapps.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # First you need to install a chromium browser in your runner
      # - name: Install Chromium
      #   run: sudo apt-get install chromium-browser firefox openjdk-8-jdk

      # fetch the current ref
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.7

      # Use Node version above 14.x you want to use
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Install your dependencies (with yarn, npm no matter)
      - run: npm install
        name: Install dependencies

      # Run your test with the same command you uses locally
      - run: npm run test:ci
        name: Running E2E tests
